name: Docker Image CI

on:
  push:
    branches:
      - staging
      - trying

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Pull submodules
        run: git submodule update --init --recursive

      - name: Build OpenedX
        run: docker build . --file ./Dockerfile --tag ghcr.io/eol-uchile/edx-uabierta:${GITHUB_SHA} --tag ghcr.io/eol-uchile/edx-uabierta:latest --target base

      - name: Build static files for OpenedX S3
        run: docker build . --file ./Dockerfile --tag ghcr.io/eol-uchile/edx-uabierta:s3-static-${GITHUB_SHA} --tag ghcr.io/eol-uchile/edx-uabierta:s3-static-koa --target s3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: eolito
          password: ${{ secrets.CR_PAT }}

      - name: Push
        run: |
          docker push ghcr.io/eol-uchile/edx-uabierta:${GITHUB_SHA}
          docker push ghcr.io/eol-uchile/edx-uabierta:latest
          docker push ghcr.io/eol-uchile/edx-uabierta:s3-static-${GITHUB_SHA}
          docker push ghcr.io/eol-uchile/edx-uabierta:s3-static-koa
