name: Docker Image CI

on:
  push:
    branches:
      - staging
      - trying

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Pull submodules
        run: git submodule update --init --recursive

      - name: Build OpenedX
        run: docker build . --target base --file ./Dockerfile --tag eoluchile/edx-uabierta:${GITHUB_SHA} --tag eoluchile/edx-uabierta:latest

      - name: Build static files
        run: docker build . --target s3 --file ./Dockerfile --tag eoluchile/edx-uabierta:s3-static-${GITHUB_SHA} --tag eoluchile/edx-uabierta:s3-static-juniper

      - name: Push
        run: |
          echo "${DOCKERHUB_PASSWORD}" | docker login --username ${DOCKERHUB_USER} --password-stdin
          docker push eoluchile/edx-uabierta:${GITHUB_SHA}
          docker push eoluchile/edx-uabierta:latest
          docker push eoluchile/edx-uabierta:s3-static-${GITHUB_SHA}
          docker push eoluchile/edx-uabierta:s3-static-juniper
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
